name: temtem_api_wrapper
description: Wrapper for all the methods of the unofficial Temtem REST API.
version: 0.1.1+4
homepage: https://github.com/stevenklar
repository: https://github.com/stevenklar/temtem_api_wrapper/

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4

dev_dependencies:
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/temtems.json